name: Publish artifacts

on:
  release:
    types: [published]

concurrency: release-${{ github.event.release.tag_name }}

env:
  HELM_VERSION: v3.11.3
  SEMVER_VERSION: 3.4.0
  REGISTRY: ghcr.io
  CHART_DIRECTORY: chart
  # COP_REPOSITORY:
  # COP_CHART_BASE_DIRECTORY:

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Run validations
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Validate chart version
      run: |
        chart_version=$(yq .version $CHART_DIRECTORY/Chart.yaml)
        if [ "$chart_version" != "${{ github.event.release.tag_name }}" ]; then
          >&2 echo "Version in $CHART_DIRECTORY/Chart.yaml ($chart_version) does not match release version (${{ github.event.release.tag_name }})."
          exit 1
        fi

  publish-to-packages:
    name: Publish chart to github packages
    runs-on: ubuntu-24.04
    needs: validate
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - uses: azure/setup-helm@v5
      with:
       version: ${{ env.HELM_VERSION }}

    - name: Create package
      run: |
        helm package --version ${{ github.event.release.tag_name }} $CHART_DIRECTORY

    - name: Login to the OCI registry
      run: |
        helm --registry-config $RUNNER_TEMP/helm-config.json registry login $REGISTRY -u ${{ github.actor }} --password-stdin <<< ${{ github.token }}

    - name: Upload package
      run: |
        chart_name=$(yq .name $CHART_DIRECTORY/Chart.yaml)
        file=$chart_name-${{ github.event.release.tag_name }}.tgz
        repository=$REGISTRY/${{ github.repository }}
        helm --registry-config $RUNNER_TEMP/helm-config.json push $file oci://${repository,,}

